spring:
  application:
    name: config-server
    # gitπ‹¿Ì≈‰÷√
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chubenli/springCouldConfig.git/
          searchPaths: config_server/resources
          username: username
          password: password
server:
  port: 7001
